# Generated by Django 3.2 on 2021-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0003_alter_temp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='reader_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
