# Generated by Django 3.2 on 2021-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0004_temp_reader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
