# Generated by Django 3.2 on 2021-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0005_alter_temp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
