# Generated by Django 3.2 on 2021-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_taken', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
