# Generated by Django 3.2 on 2021-04-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0003_alter_temp_time_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='time_taken',
            new_name='created_date',
        ),
    ]
